sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/ci"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: p5NiJoV4BV36xy/9CVMYIes5ks2ieOJS6GjzHPu8sqLTat8gKvugRgLkVjcy5dEqm6X5zibUEVMbFeU0Baw/QOtz1oZzpIZh2OrbUGBeI5bY9jYbfaBNtAYvwl+Izh/6bF6NFEn0lT7WE1XiPBQsif2HO6Ov8/ARHcQ5t7gJRnqG2LApuat+Qt/CZ4K+W6SBJzH7CkHOjifIS8EBf+JS8ESO9vHaGXnvDWduxRyoUCs184QkyH47RvgIdoDmeHk+XtGkq7cks4QvHtC32yYAQI/hj9OSf+cUC/7XZOLFS22QqKGyRa5tTMlnwg4Exoc01t1yB+OyjGnaQauYVlXf91f0QSgN+8uyoSLl57Unaz4uKLrcr4QK8PmGyVXEeHJMY+2M8hY2JvpYFCcUUXoFygCh2jvTSTUVmatJBaP4GF4xOjQQOzYCJjwzjinzdTyYXPo3m9Cy/0zvZUJgNFR23CXpapuiHbkpyKlvlzBUae0uxjUv2TWtGmXUxbNeBb+ReBmdjWlhyTHdPng8QEAkr7nhJgJ75ChQ+jFWNkz+FNOcsStMgZSaKZFQ6dLNicGpUq5EzQBbzgUNY1OKhXMKn2B+Owgd3FxhfcWVL4xyFwHkRIhUXlyHL1RBHwSpXPb6SBhdMm5cjXDY+ElUSbvxMJ5X1VAMvmb2A4O5g9b90CA=
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
