sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/ci"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: "S1LNOcwI0VxN3a7xV0vVZjqk1J/sBV7pvo9t2nC2odXjwlCDB7vbbbbzyV+CN5LDD4f1kz3fpxFq6ZDgkys12/nhqOhykY1XAVkEaWZG773/jbRjtRwIPy2c48BZkL41IhZjwqw5uE2d3xk8BLozdy/xX7Avx2+qxtBscOXAJ7HRYMHVhbV+zzyNLcUO6HpBzmLJnSpAEsE2sqTfy/SHmx/5RvQuXdG1oQMBIbfcWOYWJ6sGnCEfYf6BsdH/bB69R8IU7+1CJyDcvd7fHa7Yku48k/E5nC37jLOU+CckIZ6AjMWd6noL+Bps79he8mK2mZsFBjtTswQHOOJzcMEA1gla7537HtLQuYLjFdBgQZKTZPfHhBG7ykAvJlsgAFf0KLopHrHAjjd+2GKM+svPnI4nd0PQCddcA6wvshdKiHInpV0vF7zp/31RiFAVF7Vnr0Dip8xIyX+eSD8FjcAhC+k+iInckdfw/HAJ7sBtU+s79yhW/5w0esOSnU/hIqhLzqWbLggNUu/hDoMx0CEcAeSy4UWkAIm/hInfnh/Yba7lFUk3ah9DaBct3z0yt4/Bx5YIQoGPsASr35wlmWoElVXLwlh0gHaKCHyadyw24DrX1eyGSW3tPEL7d71X3rDrL2dVcEd4DJ4msw/XgISIL7DImhGrJuaQRB4PNcmwwgs="
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
