sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/ci"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: "Xyveo/unlzONjYFzCRfuVSZOv+3X+Gj62sF+vPILs5mDI+RH5IHG2Vzqrf/8hBXQ2WT7zpJT4+/vp4rMvzBDizT/qnOl/1fEoelbePdTBb9kkQSaXWOI16S5OGeJHU3EEpIH+rt5wTJdtIWQ44iSHyHYKbvS0uxWYTpVyu72qK9eg01E28vJRw+AKUuk+PPolMtMBRAR/gQORFGj6Tt72RLtVMGNZi6YaSefkt4VJ7Q7qQDXxpZSbZnO8Hv7SpilLcsCxHkPuTNs7sxuX54SAHBmwn2iCxgI/S9Zl5H5u+FaOwnPphA6FrPneEBzLTGd33wH/yZVygMYHIocrvbo42anRXgBHyz8mdX4U7ptD3Q4H+OusTJIOeJz9I4/Bx2tLS3eJMeBLTtbKjQWmWuYYmVhNxIGOu3wypjMsG9edFRVQqW8+a9aAptrAyg4pAkxjceUDTVr5vZ3V/+EMec/3pLZxvNB3Si7rgLr83svXENVyrFdiKUHiFQ0pJauUN8WyqPNBneUARcoVvhvsgCSH7/oBp5XI+j/kgWTucSGR/v/D4hY+s9KsWTg9Y3KVXCVerKxzbcJY7nNPj7gnISzOPn87Qn+WAwU14Q2wJVRaOnCFWvaOjTAkYrgvwKbTKt+BOrX/qmhLpujn2p3ruVdB6EE4O5eRk8gjkjaCDANLRs="
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
