sudo: required
services:
  - docker

env:
  global:
    - secure: AxdiEbfbcYAnUDta9LdtT6g22KLUe/Mf3VoQBKUtYmTDg1S3oeDvjIPH/xSuWzsvu738NE51/oTwvcfVseJhRtdSarOc79F1jKnGbUYedtP6N47hfp7xosIigU1JlnEBV3P4u7tbAnASg/Q95waG5FVrd7uh2EBfCTrHKXkdnJQck5P2lh9g16MNiQr7WEo95tXGDhNNKbLpfhMl9xANyKTpYe6O2GgaywPpDTOI65NgY+YA59zj6f/ZFtgbqWCQPXvwvwcqi12AfcoBDeon98dvDEuXCgdMyYMgU0oZd8t4gulmR3argFTSOFZV3ufEM9J2Az323EHI2a+r2pnla/kK9+px8D3c9Xk0NPIngqy2/L6+zwtGQh2QiprBwfiS/rwbZG8G5YF5xDAIRsPTYriUnIUNDy8RbGnumxjm0KVlBvAs5nA0bbl7Dtj/fRE7fIrfkxeAlKYmILhn/JG7k7fekbdyScxOxHBO8VedtV2aX7vlxSce0pdPkbtEFFXmMEwX4JNbHnIRwZldGHCpC01OJ7XT7NpnynF4DKT7buNY+TaVdO7Vr/fwyY/1XJk/sC7f1XB79BjVb4CYmariUXBG+nT9/9wC/rJGuU4nK7C8Bm1qUhNE0nAjViCXc9ew5s7zGOiaP9bTYg4DvaC3rOqZPCWX9NESRVyRlQKAYpI=
    - secure: Yx/hWeG2EZV25A5015Y9Onnv5oZvamEZeISQ9OtmJ0nsjJBq6uRZUI0YxWiaeNRzI/7uRpbE45BMMiWZmIZlT1CXfOKyMIPouJFDiXEEEipgX2K3yuj0LCaP6ghUN0gZdSSP8eCOAlZkJ0G0IeqqjmIQixhld/9HzLjcaJZ+zp9gULI6UkEtX/A1T+0llhK6qONVJlDIvjyyBQWePGpuAsKl4DFui9UZO/M7rE2c6sgCn2S6LbfVJUcJkpblP7RPlIukpiFKgsajvqnZNwPltepE0W136NJ8IlNHgh56oraqgTMLvAyuYn6wAIxb0elpDTxjlxCfflrU8O5U1tyM0MLlZgtXYVCXuIn12H49rwYtC77ooK7IHhzSoIBtbEibX9FSdGTKitDDP+W+8SPjipeQfcVahTJLs9qWk869ASYAxiKvOWP3UnySbBGXTMOvFWLQIuy3fwpDaNryy45d8RQqmwztZ0ikaqyi+3rRGJZQnaXO52+wLBjNdeBt2XW29yzM8Vl7Jxqg4WbatNcRt6R7v9+pkxkSParo+1fhPu3NMZyIy/q8ZxI2e2Q2T//hdZVCvEUeY31cULG5ugRnOUSvUpUKp/+DUH90bSfS8TJ1uW1Ph8VS711rl59ucb1RpHi4VN2gDJEKUXRtFJj8XohugKnrXJrdirMaF8w8/78=
    - secure: "ln4rP+gtJ8UxeH4kJ6Ns1JQ+HcsEowDBlGO3B/zMoA3ZnNMIS9vU6aOg78ikeowgMvQFzUowMJtsd0iEsUTzs13j22/UEaInAFd/slFmFhLPmntVviP/kh95agoWA2oeNYYBDDTnHwKstu3FM+moerzpVaNfRn821W5VJhK16MDx/YbHVI53wFslKk/PXfjwAzAnZIN1+RnSzViKl0DwQs0iABAbZfXQKtxE9NyqZkNR5a4QteT+B0Lxn5iC67oTkjk7MKhBbEO9D9Zm5tuwRZjtWuFyZg0BoItz2v7xt6eshz1JDvzny/bGhISaXU3eBdxz12Zy0YNx4eOTzmWaU9A+Yfs4yBmYrESnuJmWND6kxuxeD9ynZDpgoccqQ3yx5PFu6io0ITlxLod0e3iXx3KDA9+nBVm+u2InHvUv6A90Qk6H8QgW37FjWnpYQnXG2N6idC5OzJZEUzk0Q6yceZ9O57z0onbL3aXGrgbu9RICBOCfT00gpwG+it5rC7VynTwKk+Z2aVP1WcroK6eyDVFeExsxzWAxK70HGsPDd7pjNtWPg8uAc5Qc3+SXcbpypw3GczSnzWrhVGKgoIasBXNfVMJH6j8cpINN5zorzxv97wmxzjbQPBRjDH0RkK3gqQUYTQFgifnoThxl/6yGoYdneDJlWpQOLLECyyqGWPk="

matrix:
  include:
    - language: python
      python: 3.8
      script: "./bin/ci"
      deploy:
        - provider: pypi
          user: dev-im
          edge:
            source: ssbarnea/dpl
            branch: master
          password:
            secure: hhjn47GalCnADFUsLerOZALSHISeJbXyZ3N2UzChGsO3y3mERY7TD5eGFgXSkr+KlOq3Z96Im+N2f4TviRo9F87i0Z1jYAIIURDYFTJ90UQUugdyY5hjuPDDUYbEZbkcZVroW3Uq9dUpe4KcAnVFZmwIT0DEUTEgdyNzgkxMNBEobu/ZAu2tkWHu6PTWaJcpp+jII3vpay1o3HJbGdrbX9DLyC9ODHG7XJuePddQmDLuOTKOfnNxqo1tBkaw3a49bW2G1JWYpfof7l8AMaeCikRownAd0NrolDkRc19VfflvSe4w1FMYRGnZy1IJRo16olQEQiyDp8vBbAFe0xq6yncUsf12wXyRGFQqDgJXJImm0lg3oj8/4ag+ZxR8XvxGEgb+IWuqy+CD9bAVBbKRWQKeCgg2PQjTl7INoDIAaJ8f/Z65fhSB3uPZ1FlE8pBnNSFF0Lma2HGp1fIFM+jEH+WLbZKrUvYTXYvbfTUMwY41+u6Q+PEEkhqvNslOFTn2TZXwJSk0Eyq/FfhGS4jw5Bs/ngBybVSoB4ypHClo/dJcAVCl2KDx7Pc+GI1ZxNE1D6sJnOS4E6jJJdZYC9s/UQacHvTke+G3dXii9Y9BzEd508irw2DC0s+uJnSGzUm57tWHEbNAn+noZ0dhzLwCl7Jb6Uqe5sZDHK5/CqUcZeE=
          on:
            tags: true

    - language: node_js
      node_js: 12
      script:
        - cd hmt_escrow_js
        - yarn install
        - npm run copy-contracts
        - ./bin/ci
      deploy:
        - provider: npm
          edge: true # opt in to dpl v2
          access: public
          tag: alpha
          # To deploy a new js lib version, increase the package.json version in hmt_escrow_js
          # and uncomment the below with your branch name
          # on:
          #   branch: npm-publish-js


notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=

