sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/ci"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: "huK1A17R5tb2V2SKrKLznk38C9v/oGbEFptdC6xMXV1smPe47+OvA4h0t1u5oeobFJDTZ6pcs166PR3sYzxoEjgeE0Y3h7Nm14LfnpCTx+cdvMDXvjKtkIJxruHRzUBvLCJebqgkD0DJXy+Y8YcFQ4tCCOy3WL0aFg131Xrf8J3VcgPkkLMtV+mvTk4+sFYcHO0ZX1E6FrlTOl1Uvnv1kTM50c/ru8Ak+2kLjODF06bCNYHsnwh59Yx6nK1hsOs8fO5AJJOYswb67ENozLAwsP0D2SW0xqo6I1jm0FObE2nKpKa9swpYy95qVMDuXCzsl5MAdmNQIhPQu8PQelSYcRm+88b7s7DDcuc/WvKtSTF5T35BMn0SKycQ1b0HBUji/A6w8z629Fb3IgXCcJCDaIrrbBVCHqFHJoSLGXDjS8duWVQsZwNT1asGzjYxQsxfTg69sR/ZETCntGqT6jxmrb9feepoO4nz6RevJ0LEfRZNIw3yXxjpLppSQnfsRUM8QQdNusPvJiFPjdQCBYzAml/+f3znD4yzQGtk1X3X++i+a/q+Vk1Mh6ZKqSRK+dCrDZ0Z6po1msaEOE5Wq3ZGjjD9dH+0OOJvKGnjVn8qPgqG5STqrpxFSdPPg6dJ6k2AADYtbmmAnXiR3kJt2DNwpBZwlQU12R+QQHQMOzX8mSQ="
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
