sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/ci"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: "hhjn47GalCnADFUsLerOZALSHISeJbXyZ3N2UzChGsO3y3mERY7TD5eGFgXSkr+KlOq3Z96Im+N2f4TviRo9F87i0Z1jYAIIURDYFTJ90UQUugdyY5hjuPDDUYbEZbkcZVroW3Uq9dUpe4KcAnVFZmwIT0DEUTEgdyNzgkxMNBEobu/ZAu2tkWHu6PTWaJcpp+jII3vpay1o3HJbGdrbX9DLyC9ODHG7XJuePddQmDLuOTKOfnNxqo1tBkaw3a49bW2G1JWYpfof7l8AMaeCikRownAd0NrolDkRc19VfflvSe4w1FMYRGnZy1IJRo16olQEQiyDp8vBbAFe0xq6yncUsf12wXyRGFQqDgJXJImm0lg3oj8/4ag+ZxR8XvxGEgb+IWuqy+CD9bAVBbKRWQKeCgg2PQjTl7INoDIAaJ8f/Z65fhSB3uPZ1FlE8pBnNSFF0Lma2HGp1fIFM+jEH+WLbZKrUvYTXYvbfTUMwY41+u6Q+PEEkhqvNslOFTn2TZXwJSk0Eyq/FfhGS4jw5Bs/ngBybVSoB4ypHClo/dJcAVCl2KDx7Pc+GI1ZxNE1D6sJnOS4E6jJJdZYC9s/UQacHvTke+G3dXii9Y9BzEd508irw2DC0s+uJnSGzUm57tWHEbNAn+noZ0dhzLwCl7Jb6Uqe5sZDHK5/CqUcZeE="
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
