#!/bin/bash
echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin docker.io
docker build --tag hmt-escrow:0.8.1 .
docker tag hmt-escrow:0.8.1 hcaptcha/hmt-escrow:0.8.1
docker push hcaptcha/hmt-escrow:0.8.1