version: '3.7'

services:
  ganache-test:
    image: trufflesuite/ganache-cli:v6.12.2
    command: node /app/ganache-core.docker.cli.js --noVMErrorsOnRPCResponse --db=/ganache_data -m goat -i 1337 --hostname 0.0.0.0 --unlock 0x1413862c2b7054cdbfdc181b83962cb0fc11fd92 -g 1000 -v
    logging:
      driver: none
    ports:
      - 8547:8545

  minio-test:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devdevdev
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  minio-mc:
    image: minio/mc
    depends_on:
      minio-test:
        condition: service_healthy
    volumes:
      - ./docker-test-manifest.json:/tmp/manifests/docker-manifest.json
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio-test:9000 dev devdevdev;
      /usr/bin/mc mb myminio/manifests;
      /usr/bin/mc anonymous set public myminio/manifests;
      /usr/bin/mc cp /tmp/manifests/docker-manifest.json myminio/manifests;
      "

  launcher-test:
    build:
      context: ./launcher
    ports:
      - 3000:3000
    command: ["yarn", "start-prod"]

  exchange-test:
    build:
      context: ./exchange
    ports:
      - 3001:3000
    command: ["yarn", "start-prod"]

  recording-oracle-test:
    build:
      context: ./recording-oracle
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3005:3005
    environment:
      ETH_PRIVATE_KEY: 486a0621e595dd7fcbe5608cbbeec8f5a8b5cabe7637f11eccfc7acd408c3a0e
      ETH_HTTP_SERVER: http://ganache-test:8545
      PORT: 3005
    command: ["yarn", "start"]

  reputation-oracle-test:
    build:
      context: ./reputation-oracle
    ports:
      - 3006:3006
    environment:
      ETH_PRIVATE_KEY: 657b6497a355a3982928d5515d48a84870f057c4d16923eb1d104c0afada9aa8
      ETH_HTTP_SERVER: http://ganache-test:8545
      MINIO_HOST: minio-test
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: dev
      MINIO_SECRET_KEY: devdevdev
      MINIO_BUCKET_NAME: job-results
      PORT: 3006
    command: ["yarn", "start"]

