#!/bin/bash

set -eo pipefail
source $(pwd)/scripts/evm

### Setup EVM

# Ensure we compiled sources

npm run compile

# Gas reporter needs to run in its own evm instance
if [ "$RUN_EVM" = true  ]; then
  evm_kill
  evm_start
  sleep 5
fi

### Main

mkdir -p reports

# Run using the standalone evm instance
npx hardhat test --network hardhat ./test/*.ts $@

### Cleanup

# Exit error mode so the evm instance always gets killed
set +e
result=0

if [ "$RUN_EVM" = true ]; then
  evm_kill
fi

exit $result
