export const PROP_MAP: { [key: string]: string } = {
  createdAt: 'Created At',
  updatedAt: 'Updated At',
  status: 'Status',
  id: 'Id',
  fee: 'Fee',
  exchangeOracleUrl: 'Exchange Oracle Url',
  exchangeOracleAddress: 'Exchange Oracle Address',
  recordingOracleUrl: 'Recording Oracle Url',
  recordingOracleAddress: 'Recording Oracle Address',
  recordingOracleStake: 'Recording Oracle Stake',
  reputationOracleUrl: 'Reputation Oracle Url',
  reputationOracleAddress: 'Reputation Oracle Address',
  reputationOracleStake: 'Reputation Oracle Stake',
  networkId: 'Network Id',
  escrowAddress: 'Escrow Address',
  dataUrl: 'Url',
  data: 'Data',
  manifestHash: 'Manifest Hash',
  datasetLength: 'Dataset Length',
  annotationsPerImage: 'Annotations Per Image',
  labels: 'Labels',
  requesterAccuracyTarget: 'Requester Accuracy Target',
  requesterDescription: 'Requester Description',
  userId: 'User Id',
  tokenAddress: 'Token Address',
  price: 'Price',
  LAUNCHED: 'Launched',
  requestType: 'Request Type',
  mode: 'Mode',
};

export const VALUE_MAP: { [key: string]: string } = {
  local_ganache: 'Local Ganache',
  BATCH: 'Batch',
  IMAGE_LABEL_BINARY: 'Image Label Binary',
  PAID: 'Paid',
  LAUNCHED: 'Launched',
};
