name: Fortune tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Start containers
        working-directory: ./examples/fortune
        run: make test
