name: DeployGraphs
on:
  push:
    branches:
      - master
    paths:
      - contracts/**
      - hmt_subgraph/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hmt_subgraph
    steps:
      - uses: actions/checkout@v3
      - name: Set up JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g @graphprotocol/graph-cli
      - run: npm run compile
      - run: node ./scripts/generatenetworkssubgraphs.js matic
      - run: npm run codegen
      - run: graph auth --product hosted-service ${API_KEY}
        env:
          API_KEY: ${{ secrets.HP_GRAPH_API_KEY }}
      - run: graph deploy --product hosted-service humanprotocol/polygon
      - run: node ./scripts/generatenetworkssubgraphs.js rinkeby
      - run: npm run codegen
      - run: graph deploy --product hosted-service humanprotocol/rinkeby
      - run: node ./scripts/generatenetworkssubgraphs.js moonbeam
      - run: npm run codegen
      - run: graph deploy --product hosted-service humanprotocol/moonbeam
      - run: node ./scripts/generatenetworkssubgraphs.js bsc
      - run: npm run codegen
      - run: graph deploy --product hosted-service humanprotocol/bsc
      - run: node ./scripts/generatenetworkssubgraphs.js chapel
      - run: npm run codegen
      - run: graph deploy --product hosted-service humanprotocol/bsctest
